# Generated by Django 2.1.4 on 2018-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='no',
            field=models.IntegerField(),
        ),
    ]
