# Generated by Django 2.1.4 on 2018-12-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20181209_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='no',
            new_name='user_id',
        ),
    ]
